blank_issues_enabled: true
contact_links:
  - name: Question or Discussion
    url: https://github.com/callhenk/henk/discussions
    about: Ask questions or start discussions about the project
  - name: Security Vulnerability
    url: mailto:security@callhenk.com
    about: Report security vulnerabilities privately
